LANGUAGES = {
    "EN": {
        "title": "🎬 StreamCut AI — Cloud Panel",
        "subtitle": "Paste the YouTube link, **AI Chat Analyzer** will turn the hype moments into clips right in your browser!",
        "input_label": "🔗 YouTube Video or Live Stream Link:",
        "input_placeholder": "https://www.youtube.com/watch?v=...",
        "btn_analyze": "🔥 Analyze Stream & Cut Clips",
        "warn_link": "Please enter a valid YouTube link first!",
        "err_link": "Invalid YouTube link!",
        "status_chat": "📊 Processing chat data...",
        "status_no_moment": "ℹ️ No hype moments found matching the criteria.",
        "status_found": "🎯 Found {} potential clip moments!",
        "status_preparing": "🎬 [Clip {}/{}] {} seconds are being prepared at 1080p...",
        "status_ready": "✅ Clip {} Ready!",
        "btn_download_clip": "📥 Download Clip {} to Your Computer",
        "desktop_title": "🖥️ Want More Power?",
        "desktop_desc": "If you don't want to deal with browser tabs or want faster rendering in the background, download the **StreamCut AI Windows Desktop** application to your computer!",
        "btn_download_exe": "🚀 Download StreamCut AI Windows (.exe)"
    },
    "TR": {
        "title": "🎬 StreamCut AI — Bulut Paneli",
        "subtitle": "YouTube yayın linkini yapıştırın, **AI Chat Analizörü** en coşkulu anları tarayıcınızda kliplere dönüştürsün!",
        "input_label": "🔗 YouTube Video veya Canlı Yayın Linki:",
        "input_placeholder": "https://www.youtube.com/watch?v=...",
        "btn_analyze": "🔥 Yayını Analiz Et ve Klipleri Kes",
        "warn_link": "Lütfen önce geçerli bir YouTube linki girin!",
        "err_link": "Geçersiz YouTube linki!",
        "status_chat": "📊 Chat verileri işleniyor...",
        "status_no_moment": "ℹ️ Kriterlere uygun coşkulu bir an bulunamadı.",
        "status_found": "🎯 Tam {} adet potansiyel klip anı yakalandı!",
        "status_preparing": "🎬 [Klip {}/{}] {} saniyeleri 1080p olarak hazırlanıyor...",
        "status_ready": "✅ Klip {} Hazır!",
        "btn_download_clip": "📥 Klip {}'i Bilgisayarına İndir",
        "desktop_title": "🖥️ Daha Fazla Güç Mü İstiyorsunuz?",
        "desktop_desc": "Tarayıcı sekmeleriyle uğraşmak istemiyorsanız veya arka planda daha hızlı render almak istiyorsanız **StreamCut AI Windows Masaüstü** uygulamasını bilgisayarınıza indirin!",
        "btn_download_exe": "🚀 StreamCut AI Windows (.exe) İndir"
    },
    "ES": {
        "title": "🎬 StreamCut AI — Panel de Nube",
        "subtitle": "¡Pega el enlace de YouTube, el **Analizador de Chat de IA** convertirá los momentos más emocionantes en clips en tu navegador!",
        "input_label": "🔗 Enlace de Video o Transmisión en Vivo de YouTube:",
        "input_placeholder": "https://www.youtube.com/watch?v=...",
        "btn_analyze": "🔥 Analizar Transmisión y Cortar Clips",
        "warn_link": "¡Por favor, introduce primero un enlace válido de YouTube!",
        "err_link": "¡Enlace de YouTube no válido!",
        "status_chat": "📊 Procesando datos del chat...",
        "status_no_moment": "ℹ️ No se encontraron momentos emocionantes que cumplan con los criterios.",
        "status_found": "🎯 ¡Se encontraron {} momentos potenciales de clip!",
        "status_preparing": "🎬 [Clip {}/{}] los segundos {} se están preparando a 1080p...",
        "status_ready": "✅ ¡Clip {} Listo!",
        "btn_download_clip": "📥 Descargar Clip {} en tu Computadora",
        "desktop_title": "🖥️ ¿Quieres Más Potencia?",
        "desktop_desc": "Si no quieres lidiar con las pestañas del navegador o quieres un renderizado más rápido en segundo plano, ¡descarga la aplicación **StreamCut AI Windows Desktop** en tu computadora!",
        "btn_download_exe": "🚀 Descargar StreamCut AI Windows (.exe)"
    }
}
